### ISSUE TITLE
Texture for Load Screen GUI

### ISSUE THREAD

**Issue by DumbXBoxAcct** [snailcreature/AutomatedDefence#7]
I love this mod and I really can't say it enough!  Had one little issue with ver. 1.0.2 when I first loaded it, but it was easily corrected, so this is more of an FYI: 

I was getting a pink & black checkerboard for the loading screen GUI when I right-clicked the turret.  I delved into the textures folder for the GUI and found that when I tried to open the "auto_turret_loading.png" file, any program that I used to do it told me that the file was corrupted.  I downloaded the "auto_turret_loading.png" which you have in your source for the mod on GitHub & substituted that into the JAR file, after which the loading screen GUI came up perfectly, so it might be worth recompiling the JAR file & re-posting it.

Just a suggestion, please keep up the great work!

**Comment by snailcreature** [comment]
Thank you so much! I'm glad you're enjoying the mod.

Also thank you for bringing this to my attention. I noticed my JARs suddenly become 30MB rather than 36MB and I should have checked it out. I'll make sure to check my builds going forward. Fingers crossed it's a simple fix.

**Comment by snailcreature** [comment]
Ok, it should be fixed. I have tested it manually and uploaded it to CurseForge, just need it to be approved.

If you're interested in the solution: I use GitHub Actions to build the release versions, and within that I use `actions/checkout@v4` to copy the source files into the job. I forgot to tell `checkout` to use git-lfs (large file storage), and the only thing that affected was the GUI.

Please let me know if you find any more bugs or issues, and thanks again for bringing this one to my attention. ❤️
